server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/ms_user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=201209
spring.jpa.hibernate.ddl-auto=update

# JWT settings
app.jwtSecret=MinhaChaveSecretaMuitoSeguraChangeMe
app.jwtExpirationMs=3600000

# RabbitMQ (CloudAMQP)
spring.rabbitmq.addresses=amqps://yvrddmeo:TUWZkguRe36ts2CKjiKUDyIQ6KEwAYN9@guppy.rmq6.cloudamqp.com/yvrddmeo
broker.queue.email.name=default.email
